---
title: "ONASP"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: cerulean
runtime: shiny
---

```{r global, include=FALSE}
# Load Required Libraries
library(sp)
library(sf)
library(DT)
library(DBI)
library(rgdal)
library(RSQLite)
library(tidyverse)
library(htmltools)
library(lubridate)
library(shinyWidgets)
library(RColorBrewer)
library(flexdashboard)
library(rsconnect)
library(geojsonsf)
library(magrittr)
library(leaflet)
library(leafpop)
library(leafem)
library(plotly)
library(shiny)

# Obtain and prepare data
source("getData.R")

# Create hydrograph function
hydrograph <- function(id, df, htype){
  dataFiltered <- filter(df, ID == id)
  if (htype == "gw") {
    fig <- ggplot(data = dataFiltered, mapping = aes(x=Date, y=DTW)) +
      geom_line(color = "dodgerblue") + geom_point(color = "dodgerblue") +
      ggtitle(paste0("Groundwater level measured at ",id)) +
      ylab("Depth to Water (m)")
  }
  else if (htype == "pp") {
    fig <- ggplot(dataFiltered) +
      geom_col(mapping = aes(x=Date, y=Value), fill = "dodgerblue") +
      ggtitle(paste0("Monthly total rainfall measured at ",id)) +
      ylab("Precipitation (mm/month)")
  }
  fig <- fig + 
    scale_x_date(date_labels = "%b %Y") +
    theme(axis.text.x = element_text(angle = 45))
  return(fig)
}

# Define marker icon
marker_icon <- makeIcon(
  iconUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.8.0-beta.0/images/marker-icon.png",
  shadowUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.8.0-beta.0/images/marker-shadow.png",
)
```

Map
======================================

```{r}
# Render leaflet map
output$MyMap <- renderLeaflet({
  if (input$pointTypeMap == "Monitoring Wells") {
    points01 <- wsp_ll
  }
  else if (input$pointTypeMap == "Rain Gages") {
    points01 <- rgsp_ll
  }
  leaflet(points01) %>%  
    addTiles(group = "OSM") %>%
    addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
    addProviderTiles(providers$Esri.WorldImagery, group = "ESRI Imagery") %>%
    addProviderTiles(providers$Esri.WorldShadedRelief, group = "ESRI Relief") %>%
    addMarkers(label = ~ID, layerId = ~ID, icon = marker_icon, group = "markers", popup = ~New_Name) %>% 
    addFgb(file = watersheds_ll, group = "Watersheds", 
           stroke = TRUE, fill = FALSE, opacity = 0.8, 
           color = "navy", weight = 3) %>%
    addFgb(file = mainRivers_ll, group = "Rivers",
           color = "dodgerblue", weight = 2, opacity = 1, 
           popup = "LABEL") %>%
    addFgb(file = geology_ll, group = "Geology", popup = TRUE,
           stroke = TRUE, color = "black", opacity = 0.8, weight = 0.5,
           fill = TRUE, fillOpacity = 0.5, fillColor = "saddlebrown") %>%
    addLayersControl(baseGroups = c("OSM", "Toner Lite", "ESRI Imagery", "ESRI Relief"),
                     overlayGroups = c("Geology","Watersheds","Rivers"),
                     options = layersControlOptions(collapsed = TRUE),
                     position = "bottomleft") %>% 
    addLayersControl(baseGroups = c("OSM", "Toner Lite", "ESRI Imagery", "ESRI Relief"),
                     overlayGroups = c("Geology","Watersheds","Rivers"),
                     options = layersControlOptions(collapsed = TRUE),
                     position = "bottomleft") %>% 
    setView(lng = -80.2, lat = 7.9, zoom = 7.5)
})

# Confiure MyMap Output
leafletOutput(outputId = "MyMap", height="100%", width="100%")

# When map is clicked, show a popup sidebar with plot
observeEvent(
  input$MyMap_marker_click, {
    event <- input$MyMap_marker_click
    output$Chart1 <- renderPlotly(
      if (input$pointTypeMap == "Monitoring Wells") {
         wdata %>%
          filter(ID == event$id) %>% 
          plot_ly(x = ~Date, y = ~DTW, mode = "lines+markers", colors = "dodgerblue") %>% 
          layout(title = paste(event$id,"Hydrograph"),
                 showlegend = FALSE, 
                 plot_bgcolor = "#DCDCDC",
                 xaxis = list(title = "Date", 
                         tickformat = "%b %Y",
                         zerolinecolor = "#ffff",
                         gridcolor = "ffff",
                         rangeslider = list(type = "date")),
                 yaxis = list(title = "Depth to Water (m)",
                         zerolinecolor = "#ffff",
                         gridcolor = "ffff")) %>% 
          config(displayModeBar = FALSE)
      }
      else if (input$pointTypeMap == "Rain Gages") {
        rgdata_monthly %>%
          filter(ID == event$id) %>%
          plot_ly(x = ~Date, y = ~Value, type = "bar", colors = "dodgerblue") %>% 
          layout(title = paste(event$id,"Hydrograph"),
                 showlegend = FALSE, 
                 plot_bgcolor = "#DCDCDC",
                 xaxis = list(title = "Date", 
                         tickformat = "%b %Y",
                         zerolinecolor = "#ffff",
                         gridcolor = "ffff",
                         rangeslider = list(type = "date")),
                 yaxis = list(title = "Precipitation (mm/month)",
                         zerolinecolor = "#ffff",
                         gridcolor = "ffff")) %>% 
          config(displayModeBar = FALSE)
      }
    )
  }
)


# Panel for choices and plot
absolutePanel(
  id = "controls",  fixed = TRUE, draggable = FALSE, 
  top = 75, left = "auto", right = 25, bottom = "auto", width = 600, height = "auto",
  pickerInput(inputId = "pointTypeMap", 
              label = h4("Select what to show in map"), 
              choices = c("Monitoring Wells","Rain Gages"),
              selected = "Monitoring Wells", width = "100%"),
  plotlyOutput("Chart1", height = 10),
  style = "background-color: white; 
           opacity: 0.85; 
           padding: 20px 20px 20px 20px;
           margin: auto;
           border-radius: 5pt;
           box-shadow: 0pt 0pt 6pt 0px rgba(61,59,61,0.48);
           padding-bottom: 2mm;
           padding-top: 1mm"
)
```

Data
======================================

Sidebar {.sidebar data-width=350}
-------------------------------------

### User Input
```{r}
## Select Type of Graph
pickerInput(inputId = "pointType", 
            label = "Select what to graph/plot", 
            choices = c("Monitoring Wells","Rain Gages"),
            selected = "Monitoring Wells", width = "100%")

## Select Well(s) or Rain Gauges(s)
renderUI({
  if (input$pointType == "Monitoring Wells") {
    selectInput(inputId = "id", 
                label = "Select monitoring well(s)", 
                choices = c("All", unique(as.character(wdata$ID))),
                selected = "All", multiple = T, width = "100%", 
                selectize = F, size = 6)
  } else if (input$pointType == "Rain Gages") {
    selectInput(inputId = "id", 
                label = "Select rain gauge(s)", 
                choices = c("All", unique(as.character(rgdata_monthly$ID))),
                selected = "All", multiple = T, width = "100%", 
                selectize = F, size = 6)
  }
})
```

### Map Output
```{r}
# Render Well Location
output$NewMap <- renderLeaflet({
  if (input$pointType == "Monitoring Wells") {
    points_sp <- wsp_ll
    points_data <- wdata
  } else if (input$pointType == "Rain Gages") {
    points_sp <- rgsp_ll
    points_data <- rgdata_monthly
  }
  if (input$id == "All") {
    p <- subset(points_sp, ID %in% unique(points_data$ID))
  }
  else {
    p <- subset(points_sp, ID %in% input$id)
  }
  leaflet(p, options = list(zoomControl = FALSE)) %>%
    addTiles(group = "OSM") %>%
    addMarkers(label = ~ID, layerId = ~ID, icon = marker_icon, popup = ~New_Name)
})

# Confiure New Map Output
leafletOutput(outputId = "NewMap", height=300)
```


Row {.tabset data-width=650}
-------------------------------------

### Graph
```{r}
# Creating reactive graph
myGraph <- reactive({
   if (input$pointType == "Monitoring Wells") {
    given_date_range <- c(as.Date("2015-05-01"), as.Date("2020-04-30"))
    yrange <- c(-24, 3)
    if (input$id == "All") {
      well_data_new <- group_by(wdata, ID) 
    } 
    else {
      well_data_new <- wdata %>% group_by(ID) %>% filter(ID %in% input$id)
    }
    fig <- well_data_new %>% 
      plot_ly(x = ~Date, y = ~DTW, 
              mode = "lines+markers",
              color = ~ID, colors="Dark2",
              xhoverformat = "%Y-%m-%d", text = ~ID,
              hovertemplate = paste('<b>%{text}</b>',
                                    '<br>DTW: %{y:.2f} m', 
                                    '<br>Date: %{x}'))
  }
  else if (input$pointType == "Rain Gages") {
    given_date_range <- c(as.Date("2018-06-01"), as.Date("2021-07-31"))
    yrange <- c(-20, max(rgdata_monthly$Value) + 50)
    if (input$id == "All") {
      rgdata_monthly_new <- group_by(rgdata_monthly, ID)
    } 
    else {
      rgdata_monthly_new <- rgdata_monthly %>% group_by(ID) %>% filter(ID %in% input$id)
    }
    fig <- rgdata_monthly_new %>% 
      plot_ly(x = ~Date, y = ~Value, type = "bar", color = ~ID, colors = "Set1")
  }
  fig %>% 
    layout(title = FALSE,
           showlegend = TRUE, 
           plot_bgcolor = "#DCDCDC",
           xaxis = list(title = "Date", 
                        tickformat = "%b %Y",
                        zerolinecolor = "#ffff",
                        gridcolor = "ffff",
                        range = given_date_range,
                        rangeslider = list(type = "date")),
           yaxis = list(title = "Depth to Water (m)",
                        zerolinecolor = "#ffff",
                        gridcolor = "ffff",
                        range = yrange)) %>% 
    config(displayModeBar = FALSE)
})

# Rendering Graph
renderPlotly(myGraph())
```

### Table

```{r, echo = FALSE}
## Ask for input
pickerInput(inputId = "dataType", 
            label = "Select which type of data to display", 
            choices = c("Time Series Data","Location Data"),
            selected = "Time Series Data", width = "50%")

# Generate dynamic table
dynamic_table <- reactive({
  if (input$pointType == "Monitoring Wells") {
    if (input$dataType == "Location Data") {
      if (input$id == "All"){
        wsp@data
      }
      else {
        wsp@data %>% filter(ID %in% input$id)
      }
    }
    else if (input$dataType == "Time Series Data") {
      if (input$id == "All"){
        wdata
      }
      else {
        wdata %>% filter(ID %in% input$id)
      }
    }
  }
  else if (input$pointType == "Rain Gages") {
    if (input$dataType == "Location Data") {
      if (input$id == "All"){
        rgsp@data
      }
      else {
        rgsp@data %>% filter(ID %in% input$id)
      }
    }
    else if (input$dataType == "Time Series Data") {
      if (input$id == "All"){
        rgdata
      }
      else {
        rgdata %>% filter(ID %in% input$id)
      }
    }
  }
})

# Render dynamic table
renderDataTable(
  datatable(
    data = dynamic_table(),
    selection = 'none',
    filter = 'top',
    extensions = 'Buttons',
    option = list(
      paging = FALSE,
      scrollY = 400,
      buttons = c('copy', 'csv', 'excel'),
      dom = 'tiB')
  )
)
```


About
======================================

```{r}
htmltools::htmlTemplate(filename = "about.html")
```
