---
title: "ONASP: Observatorio Nacional de Aguas Subterráneas de Panamá"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: cerulean
---

```{r global, include=FALSE}
# Load Required Libraries
library(sp)
library(DBI)
library(rgdal)
library(RSQLite)
library(tidyverse)
library(htmltools)
library(lubridate)
library(RColorBrewer)
library(leaflet)
library(plotly)

# Read shapefiles from database
shpDB <- "data/PanamaShapefiles.sqlite"
rivers <- readOGR(dsn=shpDB, layer="rivers_main_2011", verbose=F, use_iconv=T, encoding="UTF-8")
geology <- readOGR(dsn=shpDB, layer="geologic_formations_1990", verbose=F, use_iconv=T, encoding="UTF-8")
watersheds <- readOGR(dsn=shpDB, layer="watersheds_2012", verbose=F, use_iconv=T, encoding="UTF-8")

# Open database connection and read tables
objDB <- dbConnect(drv=SQLite(), dbname="data/Estibana_v5.1.sqlite")
Head_Data <- dbReadTable(objDB, "Head_Data")
Head_Points <- dbReadTable(objDB, "Head_Points")
dbDisconnect(objDB)

# Select Well Points
wells <- filter(Head_Points, Type == "well")

# Select GW Data from Wells
wdata <- Head_Data %>% 
  filter(str_detect(ID, "PM") | str_detect(ID,"MP")) %>% 
  mutate(DTW = -1*DTW, Date = ymd(Date), ID = as.factor(ID))

# Define coordinate reference systems
crs32617 <- CRS("+proj=utm +zone=17 +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
crs4326 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84")

# Create Spatial Well Points
wsp <- SpatialPointsDataFrame(
  coords = dplyr::select(wells, X, Y), 
  data   = dplyr::select(wells, ID, Z:LTP),
  proj4string = crs32617)

# Transform Coordinates to Lat Lon
wsp_ll <- spTransform(wsp, crs4326)
rivers_ll <- spTransform(rivers, crs4326)
geology_ll <- spTransform(geology, crs4326)
watersheds_ll <- spTransform(watersheds, crs4326)

# Define Function to Plot Wells
plotWells <- function(data_table, w_name){
  ## Creating Color Pallette
  nw <- data_table$ID %>% unique() %>% length()
  wells_pal <- colorRampPalette(brewer.pal(12,w_name))(nw)
  ## Plotting
  figure <- ggplot(data = data_table, mapping = aes(x = Date, y = DTW)) + 
    geom_line(mapping = aes(color = ID), linetype = "dashed") +
    geom_point(mapping = aes(color = ID), shape = 15) +
    geom_smooth(color = "grey45") + theme_light() + 
    scale_colour_manual(values = wells_pal) +
    scale_x_date(name = "Fecha", date_breaks = "3 months", date_labels = "%b %Y") +
    labs(y = "Profundidad al Nivel Estático (m)", x = "Fecha")
  return(ggplotly(figure))
}
```


Information {.sidebar}
-------------------------------------

### Historia

En mayo de 2015 se estableció la primera red de monitoreo de niveles piezométicos (niveles freáticos) del país en la cuenca del Río La Villa. Los datos son recolectados mensualmente por personal de la Dirección Regional de Herrera del IDAAN (Emilio Díaz, Karen Azcárraga) y personal del Deparatmento de Fuentes Subterráneas del IDAAN (Abel Castillo, Gilberto Sánchez).

### ¿Qué es ONASP?

El Observatorio Nacional de Aguas Subterráneas de Panamá (ONASP) es una iniciativa para compartir estos datos con los usiarios y tomadores de decisiones, para que cuenten con información acerca del comportamiento de las aguas subterráneas de la región.

Esta aplicación web fue diseñada utilizando [R](https://www.r-project.org/) y [Github Pages](https://pages.github.com/). La funcionalidad y aspecto de la página está basada en el Observatorio de Aguas Subterráneas de California (http://ucwater.org/gw_obs/) y el Observatorio de Calidad de Aguas Subterráneas de California (https://caccr.github.io/) ambos diseñados por [Rich Pauloo](https://richpauloo.github.io/).

El código fuente puede encontrarse [aquí](https://github.com/mgcastre/ONASP/tree/gh-pages).

&copy; 2022 por [María Gabriela Castrellón](https://github.com/mgcastre).


Row {.tabset}
-------------------------------------

### Localización de Pozos

```{r}
# Add Labels for Wells
wsp_ll$New_Name <- 
  paste0('<strong>', wsp_ll$ID, '</strong>',
         '<br/>', 'Distrito: ', wsp_ll$District,
         '<br/>', 'Corregimiento: ', wsp_ll$Township, 
         '<br/>', 'Localidad: ', wsp_ll$Location) %>% 
  lapply(htmltools::HTML)

# Add Labels for Geology
geology_ll$New_Name <- 
  paste0('<strong>', geology_ll$simbolo, '</strong>',
         '<br/>', 'Formas: ', geology_ll$formas,
         '<br/>', 'Grupo: ', geology_ll$grupo, 
         '<br/>', 'Formacion: ', geology_ll$formacion) %>% 
  lapply(htmltools::HTML)

# Render Leaflet Interactive Map
leaflet(wsp_ll) %>%
  addTiles(group = "OSM") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "ESRI Imagery") %>%
  addProviderTiles(providers$Esri.WorldShadedRelief, group = "ESRI Relief") %>%
  addMarkers(popup = ~New_Name) %>%
  addPolygons(data = geology_ll, group = "Geología",
              popup = ~geology_ll$New_Name,
              stroke = TRUE, color = "black", opacity = 1,
              fill = TRUE, fillOpacity = 0.5, weight = 0.5,
              fillColor = ~colorFactor("YlOrBr", formas)(formas),
              highlightOptions = highlightOptions(color = "white", weight = 1.5, bringToFront = FALSE)) %>%
  addPolygons(data = watersheds_ll, group = "Cuencas",
              stroke = TRUE, fill = FALSE, opacity = 1,
              color = "navy", weight = 3) %>%
  addPolylines(data = rivers_ll, group = "Ríos",
               color = "dodgerblue", weight = 2,
               opacity = 1, popup = ~rivers_ll$label,
               highlightOptions = highlightOptions(color = "cyan", weight = 2.5)) %>%
  setView(lng = -80.5, lat = 8.6, zoom = 7.5) %>%
  addLayersControl(baseGroups = c("OSM", "Toner Lite", "ESRI Imagery", "ESRI Relief"),
                   overlayGroups = c("Cuencas","Geología","Ríos"),
                   options = layersControlOptions(collapsed = FALSE))
```


### Niveles Piezométricos

```{r}
# Create color palette
nw <- wells$ID %>% unique() %>% length()
wells_pal <- colorRampPalette(brewer.pal(12,"Dark2"))(nw)

# ggplot
figure <- wdata %>% 
  highlight_key(~ID) %>% 
  ggplot(mapping = aes(x = Date, y = DTW)) + 
  ggtitle("Niveles Piezométricos en Pozos de Observación") +
  geom_line(mapping = aes(color = ID)) +
  geom_point(mapping = aes(color = ID), size = 1.5) +
  geom_smooth(color = "grey45") + theme_light() +
  scale_colour_manual(values = wells_pal) +
  scale_x_date(name = "Fecha", date_breaks = "3 months", date_labels = "%b %Y") +
  labs(y = "Profundidad al Nivel Estático (m)", x = "Fecha") +
  theme(axis.text.x = element_text(angle = 45))

# plotly
ggplotly(figure) %>% 
  group_by(ID) %>%
  highlight(on = "plotly_hover", 
            off = "plotly_doubleclick",
            opacityDim = 0.2)
```

